### PR TITLE
remove third-party transpose-frame.el

### PR DESCRIPTION
**Pull request by tarsius**
Remove the bundled third-party library `transpose-frame.el`.
Since the package `transpose-frame` is available from Melpa,
there is no good reason to bundle the library.

### CODE REVIEW

**Comment by pyluyten** [comment]
So nu-mode-pkg.el should depend on transpose frame, can you add this ?

**Comment by tarsius** [comment]
I have done that now.

Because `transpose-frame` comes from the Emacswiki, it does not appear on Melpa Stable. Melpa creates stable releases from tagged commits. That doesn't work for packages coming from the wiki. I hope that will be fixed eventually, it might even be me who provides the patch to do so.

But because you depend on a snapshot version of `helm`, `nu-mode` won't be installable from Melpa Stable anyway (unless a users uses Melpa Stable *and* Melpa). You should always depend actual releases (which comes with its own issues, but the Melpa maintainers request that you do that).

Ah, I see `nu-mode` isn't actually on Melpa, so this doesn't really matter anyway.

**Comment by tarsius** [comment]
ping

**Comment by tarsius** [comment]
Thanks!

**Pull request merged**
